//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakibiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDOKUMAN
    {
        public int REC_ID { get; set; }
        public System.DateTime REC_DATE { get; set; }
        public string REC_USERNAME { get; set; }
        public int REC_USERNO { get; set; }
        public System.DateTime REC_UPDATE { get; set; }
        public string REC_UPUSERNAME { get; set; }
        public int REC_UPUSERNO { get; set; }
        public string REC_CHANGED { get; set; }
        public string REC_VERSION { get; set; }
        public string PROJE_KOD { get; set; }
        public string GOREV_KOD { get; set; }
        public byte[] BELGE { get; set; }
        public string ARSTR_1 { get; set; }
        public string ARSTR_2 { get; set; }
        public string ARSTR_3 { get; set; }
        public Nullable<decimal> ARFLOAT_1 { get; set; }
        public Nullable<decimal> ARFLOAT_2 { get; set; }
        public Nullable<decimal> ARFLOAT_3 { get; set; }
        public Nullable<System.DateTime> ARDATE_1 { get; set; }
        public Nullable<System.DateTime> ARDATE_2 { get; set; }
        public Nullable<System.DateTime> ARDATE_3 { get; set; }
        public string DOSYA_YOLU { get; set; }
    
        public virtual TBLGOREV TBLGOREV { get; set; }
        public virtual TBLPROJE TBLPROJE { get; set; }
    }
}
